CREATE DATABASE IF NOT EXISTS webapp DEFAULT CHARACTER SET utf8mb4;
USE webapp;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);